DIKO rewards can be staked immediately
arkadiko-dao/arkadiko pull request #133
Opened 2021-07-13 15:30 UTC by nieldeckx

2021-07-13 21:12 UTC, philipdesmedt requested changes
LGTM - just fix the indentation and I'll do another functional test and add a button to the new dropdowns

2021-07-13 21:12 UTC, philipdesmedt commented on clarity/contracts/arkadiko-stake-registry-v1-1.clar
> +  )
REQ: fix indentation

2021-07-14 07:00 UTC, nieldeckx commented
@philipdesmedt fixed indentation and added buttons to the new dropdowns

2021-07-14 07:06 UTC, philipdesmedt commented
@nieldeckx nice! I'll test

2021-07-16 07:39 UTC, philipdesmedt approved these changes

2021-07-16 07:39 UTC, merged