Test models
arkadiko-dao/arkadiko pull request #187
Opened 2021-08-22 13:50 UTC by nieldeckx

2021-08-24 14:42 UTC, nieldeckx commented
Made all tests a lot easier to read by using separate models and helper functions. Once this PR is merged I will start adding more tests, and add documentation where needed.

2021-08-25 11:08 UTC, philipdesmedt requested changes

2021-08-25 11:08 UTC, philipdesmedt commented on scripts/proposal-change-stacker.js
> +      'address': tx.standardPrincipalCV(deployer.address),
REQ: I don't think we have access to `deployer` in scripts?

2021-08-25 11:31 UTC, nieldeckx commented
Great catch. Fixed it.

2021-08-25 12:11 UTC, merged