fix: update clarinet and tests
arkadiko-dao/arkadiko pull request #494
Opened 2022-05-25 14:13 UTC by nieldeckx

2022-05-25 15:02 UTC, philipdesmedt requested changes
LGTM! Good work

Any idea why some tests actually changed?

2022-05-25 15:07 UTC, nieldeckx commented on clarity/tests/arkadiko-auction-engine-v4-1_test.ts
> +    call.result.expectTuple()["share-block"].expectUint(15);
Had to update a lot of block heights. I guess the deployment of contracts has changed and it now takes more blocks before the tests actually start.

2022-05-25 21:55 UTC, lgalabru commented on clarity/tests/arkadiko-auction-engine-v4-1_test.ts
> +    call.result.expectTuple()["share-block"].expectUint(15);
So, in order to be a bit more consistent with what would happen with an actual deployment on Devnet/Testnet/Mainnet, contracts are now batched by 25 (tx chaining limit).
you can work around this by generating a deployment plan with
```bash
clarinet deployment generate --simnet
```
and in the `deployments/default.simnet-plan.yaml` file, merge the batches as in turn 
```yaml
- batch
  - transaction 1
  - transaction 2
- batch
  - transaction 3
  - transaction 4
```
into
```yaml
- batch
  - transaction 1
  - transaction 2
  - transaction 3
  - transaction 4
```

clarinet test will use this file by default if it exists

2022-05-26 06:20 UTC, nieldeckx commented on clarity/tests/arkadiko-auction-engine-v4-1_test.ts
> +    call.result.expectTuple()["share-block"].expectUint(15);
@lgalabru awesome, will give it a go. Thx man! 🙏

2022-05-28 07:55 UTC, closed without merging